### ISSUE TITLE
Add images for buildings and characters

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/Medieval-life-simulator#1]
You can add pictures/icons to existing buildings and characters.

**Comment by crisner** [comment]
I would like to work on this. I am guessing we need to add images to mine, miners and blacksmiths for now? Should the blacksmiths be character icons or buildings to represent location?

**Comment by TomaszWychocki** [comment]
Ok, add images to mine, miners and blacksmiths. I think, that every object, that doesn't move shout have building icons and all moving objects should have character icons.

**Comment by TomaszWychocki** [comment]
Well done! Have you got any idea how to run this script without local server?

**Comment by crisner** [comment]
Thanks! The browser does not allow cross origin sharing from a file URL and the only solution is using a local server. I once did a workaround with one of my projects that used plain JavaScript and had a similar problem but I can't be sure it will work with this one.

**Comment by TomaszWychocki** [comment]
We need more images for recently added buildings and characters.

**Comment by crisner** [comment]
I have found a few more images that can be used. Can I work on this?

**Comment by TomaszWychocki** [comment]
Yes, you can 👍

**Comment by crisner** [comment]
@TomaszWychocki How do you feel about adding goblins for enemies? Take a look at this [sprite](https://opengameart.org/content/lpc-goblin). I can start to work on adding the appropriate animate methods for the enemy object if you are okay with this.

**Comment by TomaszWychocki** [comment]
Looks good for me. Take this task!
