### ISSUE TITLE
Can't load image or json file in p5.js

### ISSUE THREAD

**Issue by au12113** [TomaszWychocki/Medieval-life-simulator#14]
Even has commit that fixed from @TomaszWychocki. Chrome browser can't load both json and image that  
because some p5js internal change to use Fetch API in order to load some resource types, the file:// scheme seems to work only in Firefox now!
[https://discourse.processing.org/t/fetch-api-cannot-load-file/3261/3](url)

**Comment by TomaszWychocki** [comment]
As @crisner said [here](https://github.com/TomaszWychocki/Medieval-life-simulator/issues/1#issuecomment-426932511), if we want to load some images or music, we need to use local server (or Firefox). I tested first solution using xampp and it works.

**Comment by TomaszWychocki** [comment]
I have updated README.md file
