### ISSUE TITLE
Add some music/sounds

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/Medieval-life-simulator#15]
Add some background music and blacksmith, mining etc. sounds.

**Comment by TomaszWychocki** [comment]
Ok, it's your task

**Comment by nigeldelviero** [comment]
#21

**Comment by TomaszWychocki** [comment]
I think, that page loading time is too long. Maybe we should replace blackmith and mine long music with something shorter. What about playing this sounds only if blacksmiths or mines are working?

**Comment by nigeldelviero** [comment]
ok, please check my pull request #34
