### ISSUE TITLE
Change background

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/Medieval-life-simulator#16]
Let's think about background.Any ideas? What about grass texture?

**Comment by harshalitalele** [comment]
I can work on this one.
p5.js looks very interesting.

**Comment by TomaszWychocki** [comment]
Ok, do it!

**Comment by nigeldelviero** [comment]
this is interesting, i will add grass texture for background

**Comment by TomaszWychocki** [comment]
@harshalitalele was first. What about [this](https://github.com/TomaszWychocki/Medieval-life-simulator/issues/15#issue-366869057) issue?

**Comment by nrsalmon** [comment]
Is anyone currently working on this? can it be closed?

**Comment by TomaszWychocki** [comment]
I'm still waiting for @harshalitalele [#16](https://github.com/TomaszWychocki/Medieval-life-simulator/pull/25#issuecomment-427453895)
