### ISSUE TITLE
Modify warriors script

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/Medieval-life-simulator#19]
Warriors can't kill enemies without sword. They must take it from blacksmith. Every hit should damage this weapon.

Also add icon if warrior has a sword.

**Comment by crownedpigeon** [comment]
I'd like to work on this! Should the sword icon appear on the warriors, or beneath them the way iron/swords are displayed beneath blacksmith buildings?

**Comment by TomaszWychocki** [comment]
@crownedpigeon,  I think, that the best solution is to add warriors sprites without and with swords in their hands. Script should display proper warrior sprite depending on the sword health (it health == 0 then display warriors without sword)

@au12113, exactly. Maybe swords production speed should be slowed down?

**Comment by au12113** [comment]
@TomaszWychocki, yes, it should be slowed down. but we can adjust the production speed later.
