### ISSUE TITLE
Add warriors to the village

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/Medieval-life-simulator#2]
Create new class responsible for drawing and performing warriors actions.
What we need at the beginning is to create warrior, who can take a sword from blacksmith and come back to barracks.

**Comment by au12113** [comment]
I want to do this one. let me join you.

**Comment by TomaszWychocki** [comment]
Do it!

**Comment by au12113** [comment]
I recommend to separate file for each class. such as miner.js, then we can import with "<script src="script/miner.js"></script>" in index.html

**Comment by TomaszWychocki** [comment]
I was thinking about it. It's a good solution to make code cleaner.
